export function dateISO(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}
export const today = dateISO();
const departure = new Date();
departure.setDate(departure.getDate() + 3);
const base = {
  arrivalDate: today,
  departureDate: dateISO(departure),
  diet: "Regular",
  notes: "",
};
export const seedGuests = [
  {
    id: "G-1001",
    name: "Girishbhai & Taraben Patel",
    initials: "GP",
    group: "Family",
    city: "Robbinsville, NJ",
    phone: "+1 (609) 555-0192",
    count: 2,
    arrivalTime: "13:45",
    status: "Arriving",
    stay: "Samarpan",
    room: "B-204",
    transport: "Assigned",
    color: "peach",
    travel: "UA 1422 · Newark Airport",
    diet: "Diabetic",
    notes: "Wheelchair assistance at Gate 2. Ground floor preferred.",
  },
  {
    id: "G-1002",
    name: "Pravinbhai & Hansaben Shah",
    initials: "PS",
    group: "Couple",
    city: "London, UK",
    phone: "+1 (201) 555-0148",
    count: 2,
    arrivalTime: "11:20",
    status: "Checked in",
    stay: "Samarpan",
    room: "A-108",
    transport: "Not needed",
    color: "sage",
    travel: "Campus shuttle",
    diet: "Jain",
    notes: "Luggage delivered to room.",
  },
  {
    id: "G-1003",
    name: "Rameshbhai Choksi",
    initials: "RC",
    group: "Individual",
    city: "Ahmedabad, India",
    phone: "+1 (732) 555-0127",
    count: 1,
    arrivalTime: "10:30",
    status: "Checked in",
    stay: "Samarpan",
    room: "C-312",
    transport: "Not needed",
    color: "lavender",
    travel: "Amtrak · Trenton",
    notes: "Arrived with the morning group.",
  },
  {
    id: "G-1004",
    name: "Kiritbhai & Family",
    initials: "KP",
    group: "Family",
    city: "Atlanta, GA",
    phone: "+1 (404) 555-0194",
    count: 4,
    arrivalTime: "15:30",
    status: "Arriving",
    stay: "Samarpan",
    room: "",
    transport: "Needed",
    color: "blue",
    travel: "DL 0828 · Newark Airport",
    notes: "Two adults and two children. Keep the family together.",
  },
  {
    id: "G-1005",
    name: "Jatinbhai & Dharmishtaben Vora",
    initials: "JV",
    group: "Couple",
    city: "Toronto, Canada",
    phone: "+1 (416) 555-0142",
    count: 2,
    arrivalTime: "14:20",
    status: "Arriving",
    stay: "Offsite",
    room: "F-312",
    transport: "Assigned",
    color: "rose",
    travel: "AC 712 · Newark Airport",
  },
  {
    id: "G-1006",
    name: "Hiteshbhai & Bhavnaben Dave",
    initials: "HD",
    group: "Couple",
    city: "London, UK",
    phone: "+1 (201) 555-0167",
    count: 2,
    arrivalTime: "15:10",
    status: "Arriving",
    stay: "Samarpan",
    room: "C-105",
    transport: "Assigned",
    color: "peach",
    travel: "BA 189 · Newark Airport",
    diet: "Jain",
  },
  {
    id: "G-1007",
    name: "Chicago Yuvak Mandal",
    initials: "CY",
    group: "Mandal",
    city: "Chicago, IL",
    phone: "+1 (630) 555-0144",
    count: 8,
    arrivalTime: "16:00",
    status: "Arriving",
    stay: "Samarpan",
    room: "",
    transport: "Needed",
    color: "sage",
    travel: "Charter Bus 402",
    notes: "Youth group of eight. Dormitory accommodation preferred.",
  },
  {
    id: "G-1008",
    name: "Mukeshbhai Shah & Family",
    initials: "MS",
    group: "Family",
    city: "Edison, NJ",
    phone: "+1 (732) 555-0131",
    count: 4,
    arrivalTime: "11:15",
    status: "Checked in",
    stay: "Samarpan",
    room: "A-102",
    transport: "Not needed",
    color: "lavender",
    travel: "Personal car · Lot C",
    diet: "Jain",
  },
  {
    id: "G-1009",
    name: "Amitbhai & Nehaben Desai",
    initials: "AD",
    group: "Family",
    city: "Dallas, TX",
    phone: "+1 (214) 555-0119",
    count: 3,
    arrivalTime: "17:30",
    status: "Arriving",
    stay: "Offsite",
    room: "F-218",
    transport: "Needed",
    color: "blue",
    travel: "AA 119 · Newark Airport",
  },
  {
    id: "G-1010",
    name: "Meenaben Trivedi",
    initials: "MT",
    group: "Couple",
    city: "Princeton, NJ",
    phone: "+1 (609) 555-0183",
    count: 2,
    arrivalTime: "09:45",
    status: "Checked in",
    stay: "Day visitor",
    room: "",
    transport: "Not needed",
    color: "rose",
    travel: "Personal car",
    diet: "Diabetic",
  },
].map((guest) => ({ ...base, ...guest }));
export const statusTone = (status) =>
  status === "Checked in" ? "green" : status === "Arriving" ? "amber" : "gray";
export function formatTime(time) {
  if (!time) return "Not set";
  const [hours, minutes] = time.split(":");
  const h = Number(hours);
  return `${h % 12 || 12}:${minutes} ${h >= 12 ? "PM" : "AM"}`;
}
