export const roomInventory = [
  {
    id: "A-101",
    wing: "A",
    floor: "Ground floor",
    capacity: 4,
    kind: "Family room",
    property: "Samarpan",
  },
  {
    id: "A-102",
    wing: "A",
    floor: "Ground floor",
    capacity: 4,
    kind: "Family room",
    property: "Samarpan",
  },
  {
    id: "A-108",
    wing: "A",
    floor: "Ground floor",
    capacity: 4,
    kind: "Accessible room",
    property: "Samarpan",
  },
  {
    id: "B-201",
    wing: "B",
    floor: "First floor",
    capacity: 8,
    kind: "Group room",
    property: "Samarpan",
  },
  {
    id: "B-204",
    wing: "B",
    floor: "First floor",
    capacity: 4,
    kind: "Family room",
    property: "Samarpan",
  },
  {
    id: "C-105",
    wing: "C",
    floor: "Ground floor",
    capacity: 4,
    kind: "Family room",
    property: "Samarpan",
  },
  {
    id: "C-312",
    wing: "C",
    floor: "Second floor",
    capacity: 2,
    kind: "Twin room",
    property: "Samarpan",
  },
  {
    id: "C-314",
    wing: "C",
    floor: "Second floor",
    capacity: 4,
    kind: "Family room",
    property: "Samarpan",
  },
  {
    id: "F-216",
    floor: "Second floor",
    capacity: 4,
    kind: "Fairfield Inn · Family room",
    property: "Offsite",
  },
  {
    id: "F-218",
    floor: "Second floor",
    capacity: 3,
    kind: "Fairfield Inn · Family room",
    property: "Offsite",
  },
  {
    id: "F-310",
    floor: "Third floor",
    capacity: 2,
    kind: "Fairfield Inn · Twin room",
    property: "Offsite",
  },
  {
    id: "F-312",
    floor: "Third floor",
    capacity: 2,
    kind: "Fairfield Inn · Twin room",
    property: "Offsite",
  },
];
export const initialLinen = { "A-108": 1, "C-314": 2 };
