"""Convert the Contacts sheet to the browser registration lookup database.

Usage: python3 scripts/build_contacts.py /path/to/Contacts.xlsx
Requires openpyxl. Only the five registration fields are exported.
"""
import argparse
import json
import re
from pathlib import Path

import openpyxl

HEADERS = ('Phone Number', 'Names of Participants (Yajmano)', 'Email', 'Zip Code', 'City, State')
FIELDS = ('phone', 'name', 'email', 'zipCode', 'cityState')


def text(value):
    if value is None:
        return ''
    if isinstance(value, (int, float)) and value == int(value):
        return str(int(value))
    return str(value).strip()


def build(source, destination):
    if destination.suffix not in ('.js', '.json'):
        raise ValueError('Contact export must be a JS database or private JSON file.')
    workbook = openpyxl.load_workbook(source, read_only=True, data_only=True)
    try:
        sheet = workbook['Contacts']
        rows = sheet.iter_rows(values_only=True)
        if tuple(next(rows)) != HEADERS:
            raise ValueError('Contacts sheet must have the five expected column headers in order.')
        contacts = []
        for row_number, row in enumerate(rows, 2):
            if not any(value is not None for value in row):
                continue
            contact = dict(zip(FIELDS, map(text, row)))
            phone = re.sub(r'[^0-9]', '', contact['phone'])
            if len(phone) == 11 and phone.startswith('1'):
                phone = phone[1:]
            if len(phone) != 10:
                raise ValueError(f'Row {row_number}: expected a 10-digit phone number, optionally prefixed with 1.')
            contact['phone'] = phone
            if not contact['name']:
                raise ValueError(f'Row {row_number}: name is required.')
            # Restore leading zeroes for numeric US ZIP cells; text values stay intact.
            if isinstance(row[3], (int, float)):
                contact['zipCode'] = contact['zipCode'].zfill(5)
            contact['id'] = str(row_number)
            contacts.append(contact)
        if not contacts:
            raise ValueError('No contacts found; refusing to replace the database with an empty file.')
        payload = json.dumps({'version': 1, 'contacts': contacts}, ensure_ascii=True, separators=(',', ':'))
        content = ('// Generated by scripts/build_contacts.py. This browser-readable contact database is public when published.\nwindow.REG_CONTACTS_DB = ' + payload + ';\n') if destination.suffix == '.js' else payload + '\n'
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding='utf-8')
        print(f'Exported {len(contacts)} records / {len({c["phone"] for c in contacts})} phone numbers ({len(content.encode())} bytes).')
    finally:
        workbook.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'reg' / 'contacts-db.js')
    args = parser.parse_args()
    build(args.source, args.output)
